Completion:
  AllScopes: true
Diagnostics:
  MissingIncludes: Strict
  UnusedIncludes: Strict
Hover:
  ShowAKA: true
InlayHints:
  BlockEnd: true
  DeducedTypes: true
  Designators: true
  Enabled: true
  ParameterNames: true
  TypeNameLimit: 0
