- defaults:
    link:
      create: true
      relink: true

- shell:
  -
    command: [git submodule sync --recursive, Syncing submodules]
    stdout: true
    stderr: true
  -
    command: [git submodule update --init --recursive, Updating submodules]
    stdout: true
    stderr: true
  -
    command: cd tools/LS_COLORS && ./install.sh
    description: Installing LS_COLORS script
    stdout: true
    stderr: true
  -
    command: [tools/install/install-vim-plug.sh, Installing vim-plug]
    stdin: true
    stdout: true
    stderr: true
  -
    command: [nvim +PlugInstall +qall, Installing neovim plugins]
    stdin: true
    stdout: true
    stderr: true
  -
    command: [tools/install/install-fira.sh, Installing FiraCode nerd fonts]
    stdin: true
    stdout: true
    stderr: true
  -
    command: [bat cache --build, Adding Gruvbox bat theme]
    stdin: true
    stdout: true
    stderr: true
  -
    command: [tools/bat-extras/build.sh --prefix="$HOME"/.local --install, Installing bat-extras]
    stdin: true
    stdout: true
    stderr: true

- clean: ['~']

- link:
    ~/.clang-format: clang/clang-format
    ~/.cmake-format.py: cmake/cmake-format.py
    ~/.config/bat: config/bat
    ~/.config/nvim/coc-settings.json: vim/coc-settings.json
    ~/.config/nvim/init.vim: vim/vimrc
    ~/.config/vifm: config/vifm
    ~/.config/watson/config: config/watson/config
    ~/.gdbinit: tools/gdb-dashboard/.gdbinit
    ~/.gdbinit.d:
    ~/.gitconfig: git/gitconfig
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.sage:
    ~/.tmux.conf: tools/.tmux/.tmux.conf
    ~/.tmux.conf.local: tmux/tmux.conf.local
    ~/.vim:
    ~/.zsh:
    ~/.zshrc: zsh/zshrc
