- defaults:
    link:
      create: true
      relink: true

- create:
  - ~/.local/bin

- shell:
  -
    command: git submodule sync --recursive
    description: Syncing submodules
    stdout: true
    stderr: true
  -
    command: git submodule update --init --recursive
    description: Updating submodules
    stdout: true
    stderr: true
  -
    command: cd tools/LS_COLORS && ./install.sh
    description: Installing LS_COLORS script
    stdout: true
    stderr: true
  -
    command: |
        if [[ ! -d "$HOME"/.config/nvim ]]; then
            git clone https://github.com/kevineato/CosmicNvim.git "$HOME"/.config/nvim
        fi
    description: Installing neovim plugins
    stdout: true
    stderr: true
  -
    command: tools/install/install-fira.sh
    description: Installing FiraCode nerd fonts
    stdout: true
    stderr: true
  -
    command: |
      if [[ -x "$(whence -p bat)" ]]; then
          bat cache --build
      fi
    description: Adding Gruvbox bat theme
    stdout: true
    stderr: true
  -
    command: |
      if [[ -x "$(whence -p bat)" ]]; then
          found=true
          for file in tools/bat-extras/src/*.sh; do
              found=$found && [[ -x "$HOME"/.local/bin/"$file" ]]
          done
          if [[ ! $found ]]; then
              tools/bat-extras/build.sh --minify=none --no-verify --prefix="$HOME"/.local --install
          fi
      fi
    description: Installing bat-extras
    stdout: true
    stderr: true

- clean: ["~"]

- link:
    ~/.clang-format: clang/clang-format
    ~/.clang-tidy: clang/clang-tidy
    ~/.cmake-format.py: cmake/cmake-format.py
    ~/.config/bat: config/bat
    ~/.config/nvim/lua/cosmic/config: config/nvim/config
    ~/.config/nvim/lua/snippets: config/nvim/snippets
    ~/.config/vifm: config/vifm
    ~/.config/watson/config: config/watson/config
    ~/.gdbinit: tools/gdb-dashboard/.gdbinit
    ~/.gdbinit.d:
    ~/.gitconfig: git/gitconfig
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.sage:
    ~/.tmux.conf: tools/.tmux/.tmux.conf
    ~/.tmux.conf.local: tmux/tmux.conf.local
    ~/.zsh:
    ~/.zshrc: zsh/zshrc
