export ZSH_HOME="$HOME/.zsh"

[ -f "$ZSH_HOME/export.zsh" ] && source "$ZSH_HOME/export.zsh"

[ -f "$ZSH_HOME/oh-my-zsh.zsh" ] && source "$ZSH_HOME/oh-my-zsh.zsh"

[ -f "$ZSH_HOME/alias.zsh" ] && source "$ZSH_HOME/alias.zsh"
[ -f "$ZSH_HOME/function.zsh" ] && source "$ZSH_HOME/function.zsh"

if [ -f "$ZSH_HOME/local.zsh" ]; then source "$ZSH_HOME/local.zsh"; fi

if [ -f "$HOME/.skim/shell/completion.zsh" ]; then source "$HOME/.skim/shell/completion.zsh"; fi
if [ -f "$HOME/.skim/shell/key-bindings.zsh" ]; then source "$HOME/.skim/shell/key-bindings.zsh"; fi

[ -f "$HOME/.dircolors" ] && eval "$(dircolors $HOME/.dircolors)"
[ -x "$(command -v fasd)" ] && eval "$(fasd --init auto)"

# Widgets
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu

autoload -Uz copy-earlier-word
zle -N copy-earlier-word

# Key bindings
for ((i=1; i < 10; i++)); do
  bindkey -M viins '^['$i digit-argument
done

bindkey '^[.' insert-last-word
bindkey '^[;' copy-earlier-word
bindkey '^[h' backward-char
bindkey '^[l' forward-char
bindkey '^[H' backward-word
bindkey '^[L' forward-word
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey '^Z' history-beginning-search-menu
bindkey "${terminfo[kcbt]}" reverse-menu-complete

setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ -f "$HOME/.p10k.zsh" ] && source "$HOME/.p10k.zsh"
