# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH_HOME="$HOME/.zsh"

[[ -f "$ZSH_HOME/export.zsh" ]] && source "$ZSH_HOME/export.zsh"

[[ -f "$ZSH_HOME/oh-my-zsh.zsh" ]] && source "$ZSH_HOME/oh-my-zsh.zsh"

[[ -f "$ZSH_HOME/alias.zsh" ]] && source "$ZSH_HOME/alias.zsh"
[[ -f "$ZSH_HOME/function.zsh" ]] && source "$ZSH_HOME/function.zsh"

if [[ -f "$ZSH_HOME/local.zsh" ]]; then source "$ZSH_HOME/local.zsh"; fi

# if [[ -f "$HOME/.skim/shell/completion.zsh" ]]; then source "$HOME/.skim/shell/completion.zsh"; fi
# if [[ -f "$HOME/.skim/shell/key-bindings.zsh" ]]; then source "$HOME/.skim/shell/key-bindings.zsh"; fi

if [[ -f "$HOME/.dircolors" ]]; then eval "$(dircolors $HOME/.dircolors)"; fi
if [[ -r "$HOME/.local/share/lscolors.sh" ]]; then source "$HOME/.local/share/lscolors.sh"; fi
if [[ -x "$(whence -p fasd)" ]]; then eval "$(fasd --init auto)"; fi

# Widgets
autoload -Uz copy-earlier-word
zle -N copy-earlier-word

# Key bindings
for ((i=1; i < 10; i++)); do
    bindkey -M viins '^['$i digit-argument
done

bindkey '^[.' insert-last-word
bindkey '^[;' copy-earlier-word
bindkey '^[h' backward-char
bindkey '^[l' forward-char
bindkey '^[H' backward-word
bindkey '^[L' forward-word
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey "${terminfo[kcbt]}" reverse-menu-complete

setopt extendedglob
setopt histignorealldups
setopt histignorespace
setopt magicequalsubst
# setopt rematchpcre

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
