export ZSH_HOME=$HOME/.zsh

[ -f $ZSH_HOME/export.zsh ] && source $ZSH_HOME/export.zsh

[ -f $ZSH_HOME/oh-my-zsh.zsh ] && source $ZSH_HOME/oh-my-zsh.zsh

[ -f $ZSH_HOME/alias.zsh ] && source $ZSH_HOME/alias.zsh
[ -f $ZSH_HOME/function.zsh ] && source $ZSH_HOME/function.zsh

[ -f $HOME/.dircolors ] && eval "$(dircolors $HOME/.dircolors)"
eval "$(fasd --init auto)"

# Key bindings
bindkey "^P" history-substring-search-up
bindkey "^N" history-substring-search-down
bindkey "${terminfo[kcbt]}" reverse-menu-complete

setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh
